# Generated by Django 4.2.5 on 2023-10-02 12:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Video",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("session_id", models.CharField(max_length=255, unique=True)),
                ("title", models.CharField(max_length=255)),
                ("chunk_number", models.IntegerField()),
                ("data", models.BinaryField()),
            ],
        ),
    ]
